# Generated by Django 5.2.9 on 2026-01-04 20:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rejestrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text='Unikalna nazwa identyfikująca rejestrator', max_length=200, verbose_name='Nazwa rejestratora')),
                ('opis', models.TextField(blank=True, help_text='Dodatkowy opis rejestratora', null=True, verbose_name='Opis')),
                ('aktywny', models.BooleanField(default=True, help_text='Czy rejestrator jest aktywny w systemie', verbose_name='Aktywny')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('data_modyfikacji', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
            ],
            options={
                'verbose_name': 'Rejestrator',
                'verbose_name_plural': 'Rejestratory',
                'ordering': ['nazwa'],
                'indexes': [models.Index(fields=['nazwa'], name='qrp_app_rej_nazwa_b706fc_idx'), models.Index(fields=['aktywny'], name='qrp_app_rej_aktywny_f74763_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiniaProdukcyjna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text='Nazwa identyfikująca linię produkcyjną', max_length=200, verbose_name='Nazwa linii')),
                ('url_kamery', models.URLField(help_text='Adres URL strumienia kamery (np. http://192.168.1.100:8080/stream)', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='URL kamery')),
                ('ip_plc', models.GenericIPAddressField(help_text='Adres IP sterownika PLC, z którego czytane są zmienne', protocol='IPv4', verbose_name='IP PLC')),
                ('port_plc', models.PositiveIntegerField(default=502, help_text='Port komunikacji z PLC (domyślnie 502 dla Modbus TCP)', verbose_name='Port PLC')),
                ('aktywna', models.BooleanField(default=True, help_text='Czy linia jest aktywna', verbose_name='Aktywna')),
                ('opis', models.TextField(blank=True, help_text='Dodatkowy opis linii produkcyjnej', null=True, verbose_name='Opis')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('data_modyfikacji', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('rejestrator', models.ForeignKey(help_text='Rejestrator, do którego przypisana jest linia', on_delete=django.db.models.deletion.CASCADE, related_name='linie_produkcyjne', to='qrp_app.rejestrator', verbose_name='Rejestrator')),
            ],
            options={
                'verbose_name': 'Linia produkcyjna',
                'verbose_name_plural': 'Linie produkcyjne',
                'ordering': ['rejestrator', 'nazwa'],
            },
        ),
        migrations.CreateModel(
            name='ZmiennaPLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text="Nazwa identyfikująca zmienną (np. 'Temperatura', 'Cisnienie')", max_length=200, verbose_name='Nazwa zmiennej')),
                ('adres_plc', models.CharField(help_text="Adres zmiennej w PLC (np. 'DB1.DBD0', 'MW100', 'I0.0')", max_length=50, verbose_name='Adres PLC')),
                ('typ_danych', models.CharField(choices=[('BOOL', 'BOOL - Wartość logiczna'), ('INT', 'INT - Liczba całkowita 16-bit'), ('DINT', 'DINT - Liczba całkowita 32-bit'), ('REAL', 'REAL - Liczba zmiennoprzecinkowa'), ('STRING', 'STRING - Ciąg znaków')], default='REAL', help_text='Typ danych zmiennej w PLC', max_length=10, verbose_name='Typ danych')),
                ('jednostka', models.CharField(blank=True, help_text="Jednostka miary (np. '°C', 'bar', 'm/s')", max_length=50, null=True, verbose_name='Jednostka')),
                ('wartosc_min', models.FloatField(blank=True, help_text='Minimalna wartość zmiennej (opcjonalnie)', null=True, verbose_name='Wartość minimalna')),
                ('wartosc_max', models.FloatField(blank=True, help_text='Maksymalna wartość zmiennej (opcjonalnie)', null=True, verbose_name='Wartość maksymalna')),
                ('opis', models.TextField(blank=True, help_text='Dodatkowy opis zmiennej', null=True, verbose_name='Opis')),
                ('aktywna', models.BooleanField(default=True, help_text='Czy zmienna jest aktywna i czytana z PLC', verbose_name='Aktywna')),
                ('kolejnosc', models.PositiveIntegerField(default=0, help_text='Kolejność wyświetlania zmiennej (mniejsza wartość = wyżej)', verbose_name='Kolejność')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('data_modyfikacji', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
                ('linia_produkcyjna', models.ForeignKey(help_text='Linia produkcyjna, do której przypisana jest zmienna', on_delete=django.db.models.deletion.CASCADE, related_name='zmienne_plc', to='qrp_app.liniaprodukcyjna', verbose_name='Linia produkcyjna')),
            ],
            options={
                'verbose_name': 'Zmienna PLC',
                'verbose_name_plural': 'Zmienne PLC',
                'ordering': ['linia_produkcyjna', 'kolejnosc', 'nazwa'],
            },
        ),
        migrations.AddIndex(
            model_name='liniaprodukcyjna',
            index=models.Index(fields=['rejestrator', 'aktywna'], name='qrp_app_lin_rejestr_f55e71_idx'),
        ),
        migrations.AddIndex(
            model_name='liniaprodukcyjna',
            index=models.Index(fields=['ip_plc'], name='qrp_app_lin_ip_plc_ebe6d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='liniaprodukcyjna',
            unique_together={('rejestrator', 'nazwa')},
        ),
        migrations.AddIndex(
            model_name='zmiennaplc',
            index=models.Index(fields=['linia_produkcyjna', 'aktywna'], name='qrp_app_zmi_linia_p_9ac090_idx'),
        ),
        migrations.AddIndex(
            model_name='zmiennaplc',
            index=models.Index(fields=['kolejnosc'], name='qrp_app_zmi_kolejno_0c3a7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zmiennaplc',
            unique_together={('linia_produkcyjna', 'adres_plc')},
        ),
    ]
