# Generated by Django 5.2.9 on 2026-01-05 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrp_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pomiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_kontroli', models.CharField(choices=[('Standardowe', 'Standardowe'), ('Ponowna kontrola', 'Ponowna kontrola'), ('Testowe', 'Testowe'), ('Walidacja procesu', 'Walidacja procesu')], default='Standardowe', max_length=50, verbose_name='Typ kontroli')),
                ('rodzaj_testu', models.CharField(choices=[('1', '1. Pokrycie lakierem - CuSO4'), ('2', '2. Pokrycie denka - CuSO4'), ('3', '3. Ilość oleju (talk)'), ('4', '4. Pokrycie kołnierza - CuSO4'), ('5', '5. Test kompleksowy')], max_length=10, verbose_name='Rodzaj testu')),
                ('numer_zlecenia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numer zlecenia')),
                ('komentarz', models.TextField(blank=True, null=True, verbose_name='Komentarz')),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='pomiary/', verbose_name='Zdjęcie')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('linia_produkcyjna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomiary', to='qrp_app.liniaprodukcyjna', verbose_name='Linia produkcyjna')),
                ('uzytkownik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomiary', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Pomiar',
                'verbose_name_plural': 'Pomiary',
                'ordering': ['-data_utworzenia'],
                'indexes': [models.Index(fields=['-data_utworzenia'], name='qrp_app_pom_data_ut_f9bbaa_idx'), models.Index(fields=['linia_produkcyjna', '-data_utworzenia'], name='qrp_app_pom_linia_p_5ffbf1_idx'), models.Index(fields=['uzytkownik', '-data_utworzenia'], name='qrp_app_pom_uzytkow_986536_idx')],
            },
        ),
        migrations.CreateModel(
            name='RFIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(help_text='Unikalny identyfikator karty RFID', max_length=100, unique=True, verbose_name='ID karty RFID')),
                ('numer_kj', models.CharField(blank=True, help_text='Numer KJ użytkownika', max_length=10, null=True, verbose_name='Numer KJ')),
                ('data_rejestracji', models.DateTimeField(auto_now_add=True, verbose_name='Data rejestracji')),
                ('aktywna', models.BooleanField(default=True, help_text='Czy karta jest aktywna', verbose_name='Aktywna')),
                ('user', models.OneToOneField(help_text='Użytkownik przypisany do karty RFID', on_delete=django.db.models.deletion.CASCADE, related_name='rfid_card', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Karta RFID',
                'verbose_name_plural': 'Karty RFID',
                'ordering': ['-data_rejestracji'],
                'indexes': [models.Index(fields=['card_id'], name='qrp_app_rfi_card_id_79c064_idx'), models.Index(fields=['aktywna'], name='qrp_app_rfi_aktywna_cb3483_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_kontroli', models.CharField(choices=[('Standardowe', 'Standardowe'), ('Ponowna kontrola', 'Ponowna kontrola'), ('Testowe', 'Testowe'), ('Walidacja procesu', 'Walidacja procesu')], default='Standardowe', max_length=50, verbose_name='Typ kontroli')),
                ('opis_wady', models.TextField(help_text='Szczegółowy opis zaobserwowanej wady', verbose_name='Opis wady')),
                ('komentarz', models.TextField(blank=True, null=True, verbose_name='Dodatkowe uwagi')),
                ('numer_zlecenia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numer zlecenia')),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='wady/', verbose_name='Zdjęcie')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('linia_produkcyjna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wady', to='qrp_app.liniaprodukcyjna', verbose_name='Linia produkcyjna')),
                ('uzytkownik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wady', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Wada',
                'verbose_name_plural': 'Wady',
                'ordering': ['-data_utworzenia'],
                'indexes': [models.Index(fields=['-data_utworzenia'], name='qrp_app_wad_data_ut_c41465_idx'), models.Index(fields=['linia_produkcyjna', '-data_utworzenia'], name='qrp_app_wad_linia_p_741691_idx'), models.Index(fields=['uzytkownik', '-data_utworzenia'], name='qrp_app_wad_uzytkow_cdfec4_idx')],
            },
        ),
    ]
