# Generated by Django 5.2.9 on 2026-01-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrp_app', '0002_pomiar_rfidcard_wada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liniaprodukcyjna',
            name='port_plc',
        ),
        migrations.AddField(
            model_name='liniaprodukcyjna',
            name='zmienna_numer_zlecenia',
            field=models.CharField(blank=True, help_text='Nazwa zmiennej PLC dla numeru zlecenia (np. Qrp_Order_L9)', max_length=100, null=True, verbose_name='Zmienna PLC - Numer zlecenia'),
        ),
        migrations.AlterField(
            model_name='liniaprodukcyjna',
            name='ip_plc',
            field=models.GenericIPAddressField(help_text='Adres IP sterownika PLC Allen Bradley (np. 10.11.x.x)', protocol='IPv4', verbose_name='IP PLC'),
        ),
    ]
