# Generated by Django 5.2.9 on 2026-01-16 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrp_app', '0003_add_zmienna_numer_zlecenia_remove_port_plc'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejestrator',
            name='url_kamery',
            field=models.URLField(blank=True, help_text='Adres URL strumienia kamery (np. http://192.168.1.100:8080/stream)', max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL kamery'),
        ),
    ]
