# Generated by Django 5.2.9 on 2026-01-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrp_app', '0004_add_url_kamery_to_rejestrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='liniaprodukcyjna',
            name='identyfikator_dns',
            field=models.CharField(blank=True, help_text='Identyfikator używany w URL DNS (np. l9, l2). URL będzie: qrp-{identyfikator}.canpack.ad', max_length=50, null=True, unique=True, verbose_name='Identyfikator DNS'),
        ),
    ]
