# Generated by Django 5.2.9 on 2026-01-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrp_app', '0005_add_identyfikator_dns_to_linia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liniaprodukcyjna',
            name='identyfikator_dns',
            field=models.CharField(blank=True, help_text='Identyfikator używany w URL DNS (np. l9, l2). URL będzie: qrp-{identyfikator}.canpack.ad. Wiele linii może mieć ten sam identyfikator.', max_length=50, null=True, verbose_name='Identyfikator DNS'),
        ),
    ]
