# Generated by Django 5.2.9 on 2026-01-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrp_app', '0006_remove_unique_from_identyfikator_dns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomiar',
            name='rodzaj_testu',
            field=models.CharField(choices=[('1', '1. Pokrycie lakierem - CuSO4'), ('2', '2. Pokrycie denka - CuSO4'), ('3', '3. Ilość oleju (talk)'), ('4', '4. Pokrycie kołnierza - CuSO4'), ('5', '5. Pokrycie denka roztwór - CuSO4, Pokrycie kołnierza lakierem - CuSO4, Ilość oleju na przewężeniu (talk kosmetyczny)')], max_length=10, verbose_name='Rodzaj testu'),
        ),
    ]
