# Generated by Django 5.2.9 on 2026-01-20 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db import connection


def migrate_typ_kontroli_and_rodzaj_testu(apps, schema_editor):
    """Migracja danych: tworzy rekordy w TypKontroli i RodzajTestu, aktualizuje istniejące dane"""
    TypKontroli = apps.get_model('qrp_app', 'TypKontroli')
    RodzajTestu = apps.get_model('qrp_app', 'RodzajTestu')
    
    # Utwórz typy kontroli
    typy_kontroli_data = [
        ('Standardowe', 'Standardowe', 0),
        ('Ponowna kontrola', 'Ponowna kontrola', 1),
        ('Testowe', 'Testowe', 2),
        ('Walidacja procesu', 'Walidacja procesu', 3),
    ]
    
    typy_kontroli_map = {}
    for kod, nazwa, kolejnosc in typy_kontroli_data:
        typ, created = TypKontroli.objects.get_or_create(
            kod=kod,
            defaults={'nazwa': nazwa, 'kolejnosc': kolejnosc, 'aktywny': True}
        )
        typy_kontroli_map[kod] = typ.id
    
    # Utwórz rodzaje testów
    rodzaje_testu_data = [
        ('1', 'Pokrycie lakierem - CuSO4', 0),
        ('2', 'Pokrycie denka - CuSO4', 1),
        ('3', 'Ilość oleju (talk)', 2),
        ('4', 'Pokrycie kołnierza - CuSO4', 3),
        ('5', 'Pokrycie denka roztwór - CuSO4, Pokrycie kołnierza lakierem - CuSO4, Ilość oleju na przewężeniu (talk kosmetyczny)', 4),
    ]
    
    rodzaje_testu_map = {}
    for kod, nazwa, kolejnosc in rodzaje_testu_data:
        rodzaj, created = RodzajTestu.objects.get_or_create(
            kod=kod,
            defaults={'nazwa': nazwa, 'kolejnosc': kolejnosc, 'aktywny': True}
        )
        rodzaje_testu_map[kod] = rodzaj.id
    
    # Aktualizuj typ_kontroli i rodzaj_testu w Pomiar używając SQL
    with connection.cursor() as cursor:
        # Aktualizuj typ_kontroli w pomiarach
        for kod, typ_id in typy_kontroli_map.items():
            cursor.execute(
                "UPDATE qrp_app_pomiar SET typ_kontroli_new_id = %s WHERE typ_kontroli = %s",
                [typ_id, kod]
            )
        
        # Aktualizuj rodzaj_testu w pomiarach
        for kod, rodzaj_id in rodzaje_testu_map.items():
            cursor.execute(
                "UPDATE qrp_app_pomiar SET rodzaj_testu_new_id = %s WHERE rodzaj_testu = %s",
                [rodzaj_id, kod]
            )
        
        # Ustaw domyślną wartość dla rekordów które nie mają rodzaj_testu (jeśli takie istnieją)
        # Używamy pierwszego dostępnego rodzaju testu jako domyślnego
        if rodzaje_testu_map:
            default_rodzaj_id = list(rodzaje_testu_map.values())[0]
            cursor.execute(
                "UPDATE qrp_app_pomiar SET rodzaj_testu_new_id = %s WHERE rodzaj_testu_new_id IS NULL",
                [default_rodzaj_id]
            )
        
        # Aktualizuj typ_kontroli w wadach
        for kod, typ_id in typy_kontroli_map.items():
            cursor.execute(
                "UPDATE qrp_app_wada SET typ_kontroli_new_id = %s WHERE typ_kontroli = %s",
                [typ_id, kod]
            )


def reverse_migrate_data(apps, schema_editor):
    """Odwrotna migracja danych - nie jest potrzebna"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('qrp_app', '0007_alter_pomiar_rodzaj_testu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(blank=True, help_text='Adres URL centralnego API do synchronizacji danych', max_length=500, null=True, verbose_name='URL API centralnego')),
                ('api_token', models.CharField(blank=True, help_text='Token autoryzacyjny do komunikacji z centralnym API', max_length=500, null=True, verbose_name='Token API')),
                ('log_retention_days', models.PositiveIntegerField(default=30, help_text='Liczba dni przechowywania logów synchronizacji', verbose_name='Retencja logów (dni)')),
                ('data_retention_days', models.PositiveIntegerField(default=90, help_text='Liczba dni przechowywania zsynchronizowanych rekordów przed usunięciem', verbose_name='Retencja danych (dni)')),
                ('retry_interval_minutes', models.PositiveIntegerField(default=15, help_text='Częstotliwość automatycznych prób synchronizacji zaległych rekordów', verbose_name='Interwał ponawiania (minuty)')),
                ('retry_batch_size', models.PositiveIntegerField(default=10, help_text='Liczba rekordów wysyłanych w jednej paczce podczas synchronizacji', verbose_name='Rozmiar paczki')),
                ('show_sync_status', models.BooleanField(default=True, help_text='Czy wyświetlać status synchronizacji użytkownikom', verbose_name='Pokaż status synchronizacji')),
                ('show_sync_column', models.BooleanField(default=True, help_text="Czy wyświetlać kolumnę 'Wysłano' w tabeli archiwum", verbose_name="Pokaż kolumnę 'Wysłano'")),
                ('data_modyfikacji', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
            ],
            options={
                'verbose_name': 'Ustawienia systemowe',
                'verbose_name_plural': 'Ustawienia systemowe',
                'ordering': ['-data_modyfikacji'],
            },
        ),
        migrations.AddField(
            model_name='pomiar',
            name='is_synced',
            field=models.BooleanField(default=False, help_text='Czy rekord został zsynchronizowany z centralnym API', verbose_name='Zsynchronizowano'),
        ),
        migrations.AddField(
            model_name='pomiar',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='Data i czas ostatniej synchronizacji z centralnym API', null=True, verbose_name='Data synchronizacji'),
        ),
        migrations.AddField(
            model_name='wada',
            name='is_synced',
            field=models.BooleanField(default=False, help_text='Czy rekord został zsynchronizowany z centralnym API', verbose_name='Zsynchronizowano'),
        ),
        migrations.AddField(
            model_name='wada',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='Data i czas ostatniej synchronizacji z centralnym API', null=True, verbose_name='Data synchronizacji'),
        ),
        migrations.CreateModel(
            name='RodzajTestu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(help_text="Unikalny kod identyfikujący rodzaj testu (np. '1', '2', 'test_custom')", max_length=50, unique=True, verbose_name='Kod')),
                ('nazwa', models.CharField(help_text='Pełna nazwa rodzaju testu wyświetlana użytkownikowi', max_length=500, verbose_name='Nazwa')),
                ('aktywny', models.BooleanField(default=True, help_text='Czy ta opcja jest dostępna w formularzu rejestracji', verbose_name='Aktywny')),
                ('kolejnosc', models.PositiveIntegerField(default=0, help_text='Kolejność wyświetlania (mniejsza wartość = wyżej)', verbose_name='Kolejność')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('data_modyfikacji', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
            ],
            options={
                'verbose_name': 'Rodzaj testu',
                'verbose_name_plural': 'Rodzaje testów',
                'ordering': ['kolejnosc', 'kod'],
                'indexes': [models.Index(fields=['aktywny'], name='qrp_app_rod_aktywny_dd9234_idx'), models.Index(fields=['kolejnosc'], name='qrp_app_rod_kolejno_86c735_idx')],
            },
        ),
        migrations.CreateModel(
            name='TypKontroli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(help_text="Unikalny kod identyfikujący typ kontroli (np. 'Standardowe', 'Ponowna kontrola')", max_length=50, unique=True, verbose_name='Kod')),
                ('nazwa', models.CharField(help_text='Nazwa typu kontroli wyświetlana użytkownikowi', max_length=100, verbose_name='Nazwa')),
                ('aktywny', models.BooleanField(default=True, help_text='Czy ta opcja jest dostępna w formularzu rejestracji', verbose_name='Aktywny')),
                ('kolejnosc', models.PositiveIntegerField(default=0, help_text='Kolejność wyświetlania (mniejsza wartość = wyżej)', verbose_name='Kolejność')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('data_modyfikacji', models.DateTimeField(auto_now=True, verbose_name='Data modyfikacji')),
            ],
            options={
                'verbose_name': 'Typ kontroli',
                'verbose_name_plural': 'Typy kontroli',
                'ordering': ['kolejnosc', 'kod'],
                'indexes': [models.Index(fields=['aktywny'], name='qrp_app_typ_aktywny_172022_idx'), models.Index(fields=['kolejnosc'], name='qrp_app_typ_kolejno_01caf5_idx')],
            },
        ),
        # Dodaj nowe pola jako nullable ForeignKey
        migrations.AddField(
            model_name='pomiar',
            name='typ_kontroli_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pomiary_new', to='qrp_app.typkontroli', verbose_name='Typ kontroli'),
        ),
        migrations.AddField(
            model_name='pomiar',
            name='rodzaj_testu_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pomiary_new', to='qrp_app.rodzajtestu', verbose_name='Rodzaj testu'),
        ),
        migrations.AddField(
            model_name='wada',
            name='typ_kontroli_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wady_new', to='qrp_app.typkontroli', verbose_name='Typ kontroli'),
        ),
        # Migracja danych
        migrations.RunPython(migrate_typ_kontroli_and_rodzaj_testu, reverse_migrate_data),
        # Usuń stare pola CharField
        migrations.RemoveField(
            model_name='pomiar',
            name='typ_kontroli',
        ),
        migrations.RemoveField(
            model_name='pomiar',
            name='rodzaj_testu',
        ),
        migrations.RemoveField(
            model_name='wada',
            name='typ_kontroli',
        ),
        # Zmień nazwy nowych pól na oryginalne
        migrations.RenameField(
            model_name='pomiar',
            old_name='typ_kontroli_new',
            new_name='typ_kontroli',
        ),
        migrations.RenameField(
            model_name='pomiar',
            old_name='rodzaj_testu_new',
            new_name='rodzaj_testu',
        ),
        migrations.RenameField(
            model_name='wada',
            old_name='typ_kontroli_new',
            new_name='typ_kontroli',
        ),
        # Zmień rodzaj_testu na non-nullable po migracji danych (wszystkie rekordy powinny mieć wartość)
        migrations.AlterField(
            model_name='pomiar',
            name='rodzaj_testu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pomiary', to='qrp_app.rodzajtestu', verbose_name='Rodzaj testu'),
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Kod statusu HTTP')),
                ('message', models.TextField(verbose_name='Komunikat')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data i czas')),
                ('is_success', models.BooleanField(default=False, help_text='Czy synchronizacja zakończyła się sukcesem', verbose_name='Sukces')),
                ('record_type', models.CharField(blank=True, choices=[('measurement', 'Pomiar'), ('defect', 'Wada')], max_length=20, null=True, verbose_name='Typ rekordu')),
                ('record_id', models.IntegerField(blank=True, null=True, verbose_name='ID rekordu')),
            ],
            options={
                'verbose_name': 'Log synchronizacji',
                'verbose_name_plural': 'Logi synchronizacji',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='qrp_app_syn_timesta_38c299_idx'), models.Index(fields=['is_success'], name='qrp_app_syn_is_succ_065639_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wada',
            index=models.Index(fields=['is_synced'], name='qrp_app_wad_is_sync_7dbe4f_idx'),
        ),
    ]
