# Generated by Django 5.2.9 on 2026-01-20 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrp_app', '0008_systemsettings_pomiar_is_synced_pomiar_synced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomiar',
            name='typ_kontroli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pomiary', to='qrp_app.typkontroli', verbose_name='Typ kontroli'),
        ),
        migrations.AlterField(
            model_name='wada',
            name='typ_kontroli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wady', to='qrp_app.typkontroli', verbose_name='Typ kontroli'),
        ),
    ]
