# Generated by Django 5.2.9 on 2026-01-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrp_app', '0009_alter_pomiar_typ_kontroli_alter_wada_typ_kontroli'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejestrator',
            name='dostepne_rodzaje_testu',
            field=models.ManyToManyField(blank=True, help_text='Wybierz rodzaje testów dostępne dla tego rejestratora. Jeśli puste, dostępne są wszystkie aktywne rodzaje.', related_name='rejestratory', to='qrp_app.rodzajtestu', verbose_name='Dostępne rodzaje testów'),
        ),
        migrations.AddField(
            model_name='rejestrator',
            name='dostepne_typy_kontroli',
            field=models.ManyToManyField(blank=True, help_text='Wybierz typy kontroli dostępne dla tego rejestratora. Jeśli puste, dostępne są wszystkie aktywne typy.', related_name='rejestratory', to='qrp_app.typkontroli', verbose_name='Dostępne typy kontroli'),
        ),
    ]
