# Generated by Django 5.2.9 on 2026-01-20 18:56

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_m2m_data(apps, schema_editor):
    """Migracja istniejących danych ManyToMany do modeli pośredniczących"""
    Rejestrator = apps.get_model('qrp_app', 'Rejestrator')
    RejestratorTypKontroli = apps.get_model('qrp_app', 'RejestratorTypKontroli')
    RejestratorRodzajTestu = apps.get_model('qrp_app', 'RejestratorRodzajTestu')
    
    # Migracja typów kontroli
    for rejestrator in Rejestrator.objects.all():
        # Pobierz stare powiązania (używając starej nazwy pola)
        # Musimy użyć tabeli pośredniczącej bezpośrednio
        old_table = f'qrp_app_rejestrator_dostepne_typy_kontroli'
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f'''
                SELECT typkontroli_id 
                FROM {old_table} 
                WHERE rejestrator_id = %s
            ''', [rejestrator.id])
            typ_ids = [row[0] for row in cursor.fetchall()]
            
            for idx, typ_id in enumerate(typ_ids):
                RejestratorTypKontroli.objects.create(
                    rejestrator=rejestrator,
                    typ_kontroli_id=typ_id,
                    aktywny=True,
                    kolejnosc=idx
                )
        
        # Migracja rodzajów testów
        old_table = f'qrp_app_rejestrator_dostepne_rodzaje_testu'
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f'''
                SELECT rodzajtestu_id 
                FROM {old_table} 
                WHERE rejestrator_id = %s
            ''', [rejestrator.id])
            rodzaj_ids = [row[0] for row in cursor.fetchall()]
            
            for idx, rodzaj_id in enumerate(rodzaj_ids):
                RejestratorRodzajTestu.objects.create(
                    rejestrator=rejestrator,
                    rodzaj_testu_id=rodzaj_id,
                    aktywny=True,
                    kolejnosc=idx
                )


def reverse_migrate_m2m_data(apps, schema_editor):
    """Cofnięcie migracji - usunięcie danych z modeli pośredniczących"""
    RejestratorTypKontroli = apps.get_model('qrp_app', 'RejestratorTypKontroli')
    RejestratorRodzajTestu = apps.get_model('qrp_app', 'RejestratorRodzajTestu')
    RejestratorTypKontroli.objects.all().delete()
    RejestratorRodzajTestu.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('qrp_app', '0010_add_rejestrator_customization'),
    ]

    operations = [
        # Krok 1: Utworzenie modeli pośredniczących (najpierw)
        migrations.CreateModel(
            name='RejestratorTypKontroli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktywny', models.BooleanField(default=True, help_text='Czy ten typ kontroli jest dostępny dla tego rejestratora', verbose_name='Aktywny')),
                ('kolejnosc', models.PositiveIntegerField(default=0, help_text='Kolejność wyświetlania w formularzu', verbose_name='Kolejność')),
                ('data_dodania', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('rejestrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrp_app.rejestrator', verbose_name='Rejestrator')),
                ('typ_kontroli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrp_app.typkontroli', verbose_name='Typ kontroli')),
            ],
            options={
                'verbose_name': 'Typ kontroli rejestratora',
                'verbose_name_plural': 'Typy kontroli rejestratorów',
                'ordering': ('kolejnosc', 'typ_kontroli__nazwa'),
                'unique_together': {('rejestrator', 'typ_kontroli')},
            },
        ),
        migrations.CreateModel(
            name='RejestratorRodzajTestu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktywny', models.BooleanField(default=True, help_text='Czy ten rodzaj testu jest dostępny dla tego rejestratora', verbose_name='Aktywny')),
                ('kolejnosc', models.PositiveIntegerField(default=0, help_text='Kolejność wyświetlania w formularzu', verbose_name='Kolejność')),
                ('data_dodania', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('rejestrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrp_app.rejestrator', verbose_name='Rejestrator')),
                ('rodzaj_testu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrp_app.rodzajtestu', verbose_name='Rodzaj testu')),
            ],
            options={
                'verbose_name': 'Rodzaj testu rejestratora',
                'verbose_name_plural': 'Rodzaje testów rejestratorów',
                'ordering': ('kolejnosc', 'rodzaj_testu__kod'),
                'unique_together': {('rejestrator', 'rodzaj_testu')},
            },
        ),
        # Krok 2: Migracja danych z starych tabel ManyToMany do nowych modeli pośredniczących
        migrations.RunPython(migrate_existing_m2m_data, reverse_migrate_m2m_data),
        # Krok 3: Usunięcie starych pól ManyToManyField
        migrations.RemoveField(
            model_name='rejestrator',
            name='dostepne_typy_kontroli',
        ),
        migrations.RemoveField(
            model_name='rejestrator',
            name='dostepne_rodzaje_testu',
        ),
        # Krok 4: Dodanie nowych pól ManyToManyField z through
        migrations.AddField(
            model_name='rejestrator',
            name='dostepne_typy_kontroli',
            field=models.ManyToManyField(blank=True, help_text='Wybierz typy kontroli dostępne dla tego rejestratora. Jeśli puste, dostępne są wszystkie aktywne typy.', related_name='rejestratory', through='qrp_app.RejestratorTypKontroli', to='qrp_app.typkontroli', verbose_name='Dostępne typy kontroli'),
        ),
        migrations.AddField(
            model_name='rejestrator',
            name='dostepne_rodzaje_testu',
            field=models.ManyToManyField(blank=True, help_text='Wybierz rodzaje testów dostępne dla tego rejestratora. Jeśli puste, dostępne są wszystkie aktywne rodzaje.', related_name='rejestratory', through='qrp_app.RejestratorRodzajTestu', to='qrp_app.rodzajtestu', verbose_name='Dostępne rodzaje testów'),
        ),
    ]
