# Generated by Django 5.2.9 on 2026-01-20 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrp_app', '0012_make_typ_kontroli_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejestrator',
            name='domyslny_rodzaj_testu',
            field=models.ForeignKey(blank=True, help_text='Rodzaj testu, który będzie automatycznie wybrany po otwarciu strony rejestracji pomiaru', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejestratory_domyslne_rodzaj', to='qrp_app.rodzajtestu', verbose_name='Domyślny rodzaj testu'),
        ),
        migrations.AddField(
            model_name='rejestrator',
            name='domyslny_typ_kontroli',
            field=models.ForeignKey(blank=True, help_text='Typ kontroli, który będzie automatycznie wybrany po otwarciu strony rejestracji pomiaru', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejestratory_domyslne_typ', to='qrp_app.typkontroli', verbose_name='Domyślny typ kontroli'),
        ),
    ]
