# Generated by Django 5.2.9 on 2026-01-21 14:09

from django.db import migrations, models


def set_default_csv_mappings(apps, schema_editor):
    """Ustaw domyślne wartości mapowań CSV dla istniejących ustawień"""
    SystemSettings = apps.get_model('qrp_app', 'SystemSettings')
    
    # Ustaw domyślne mapowania jeśli instancja istnieje
    try:
        settings = SystemSettings.objects.get(pk=1)
        if not settings.csv_line_mapping:
            settings.csv_line_mapping = {"Linia 2": "C020", "Linia 3": "C030"}
        if not settings.csv_machine_mapping:
            settings.csv_machine_mapping = {"Linia 2": "L020_PAL_01", "Linia 3": "L030_PAL_01"}
        if not settings.csv_inspection_mapping:
            settings.csv_inspection_mapping = {
                "1": "Pokrycie lakierem - CuSO4",
                "2": "Pokrycie denka - CuSO4",
                "3": "Ilość oleju (talk)",
                "4": "Pokrycie kołnierza - CuSO4",
                "5": "PALLETIZER - Test kompleksowy"
            }
        settings.save()
    except SystemSettings.DoesNotExist:
        pass


def reverse_set_default_csv_mappings(apps, schema_editor):
    """Cofnięcie - nie trzeba nic robić"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('qrp_app', '0013_add_default_control_type_and_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='csv_export_enabled',
            field=models.BooleanField(default=True, help_text='Czy automatycznie generować pliki CSV dla pomiarów', verbose_name='Eksport CSV włączony'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='csv_inspection_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Mapowanie kodów rodzajów testów na nazwy (JSON), np. {'1': 'Pokrycie lakierem...', '2': 'Pokrycie denka...'}", verbose_name='Mapowanie rodzajów testów'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='csv_line_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Mapowanie nazw linii na kody (JSON), np. {'Linia 2': 'C020', 'Linia 3': 'C030'}", verbose_name='Mapowanie linii (kod)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='csv_machine_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Mapowanie nazw linii na nazwy maszyn (JSON), np. {'Linia 2': 'L020_PAL_01', 'Linia 3': 'L030_PAL_01'}", verbose_name='Mapowanie linii (maszyna)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='csv_output_path',
            field=models.CharField(default='C:/QRP_Exports/', help_text='Ścieżka do folderu, gdzie będą zapisywane pliki CSV (np. C:/QRP_Exports/)', max_length=500, verbose_name='Ścieżka eksportu CSV'),
        ),
        migrations.RunPython(set_default_csv_mappings, reverse_set_default_csv_mappings),
    ]
