# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrp_app', '0015_add_allowedip_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auto_logout_enabled',
            field=models.BooleanField(default=True, help_text='Czy automatycznie wylogowywać użytkownika po okresie bezczynności', verbose_name='Automatyczne wylogowanie włączone'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_logout_timeout_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Liczba minut bezczynności po których użytkownik zostanie automatycznie wylogowany', verbose_name='Czas bezczynności przed wylogowaniem (minuty)'),
        ),
    ]
