# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrp_app', '0016_add_auto_logout_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejestrator',
            name='dla_kj',
            field=models.BooleanField(default=True, help_text='Czy rejestrator jest przeznaczony dla KJ. Jeśli odznaczone, logowanie wymaga tylko imie.nazwisko bez numeru KJ', verbose_name='Dla KJ'),
        ),
    ]
