# Generated by Django 5.2.9 on 2026-02-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrp_app', '0017_add_dla_kj_to_rejestrator'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='allowedip',
            new_name='qrp_app_all_ip_addr_4de9ae_idx',
            old_name='qrp_app_all_ip_addr_idx',
        ),
        migrations.RenameIndex(
            model_name='allowedip',
            new_name='qrp_app_all_aktywny_f2f395_idx',
            old_name='qrp_app_all_aktywny_idx',
        ),
    ]
